version: "3"
services:
  node:
    image: node:gallium-slim
    user: node
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "${PORT}:${PORT}"
    command: bash -c "npm run start:dev"