version: "3"
services:
  node:
    image: node:hydrogen-slim
    user: node
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    command: bash -c "npm run start:dev"