name: Build

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  prebuild:
    name: Run Prebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts (gallium)
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - name: npm install
        run: npm install
      - name: run prebuild
        run: npm run prebuild
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts (gallium)
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - name: npm install
        run: npm install
      - name: run build
        run: npm run build