name: Build

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts (hydrogen)
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - name: npm install
        run: npm install
      - name: run build
        run: npm run build