name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
