name: Lint

on: [push]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts (gallium)
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - name: npm install
        run: npm install
      - name: run lint
        run: npm run lint
  format:
    name: Run Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts (gallium)
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
      - name: npm install
        run: npm install
      - name: run format
        run: npm run format