name: Test

on: [push]

jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts (hydrogen)
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - name: npm install
        run: npm install
      - name: unit tests
        run: npm run test
      - name: generate codecov report
        run: npm run test:cov
      - name: upload report to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  e2e:
    name: End to end Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install node lts (hydrogen)
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen
      - name: npm install
        run: npm install
      - name: end to end test
        run: npm run test:e2e